spring:
  datasource:
    #url: jdbc:mysql://45.93.1.5:3306/fire?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: 123456
    url: jdbc:mysql://192.168.217.128:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #xa:
      #properties:
        #useInformationSchema: true
    dbcp2:
      test-on-borrow: true
      validation-query: "select 1 "
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

